### ISSUE TITLE
Many samples are broken (or lack some CSS)

### ISSUE THREAD

**Issue by EtienneM** [Scalingo/samples.scalingo.com#3]
Some of them also need to be updated to use more recent framework version

## Not working
* [ ] http://sample-ruby-rails.scalingo.io/ (also missing in the samples listing)
* [ ] https://sample-meteor-todo.scalingo.io/ Started doing it from scratch. Did it up to https://www.meteor.com/tutorials/react/collections
* [x] https://sample-meteor-phantomjs.scalingo.io/ (won't be fixed as PhantomJS is now archived)
* [x] https://sample-elixir-plug.scalingo.io/
* [x] https://sample-php-slim.scalingo.io/

## Lack CSS

* [x] https://sample-php-yii2.scalingo.io/
* [x] https://sample-java-spark.scalingo.io/hello
* [x] https://sample-php-symfony.scalingo.io/
* [x] https://sample-php-nodejs.scalingo.io/
* [x] https://sample-node-meanjs.scalingo.io/
* [x] https://sample-python-celery.scalingo.io/
* [x] https://sample-php-cron.scalingo.io/
* [x] https://sample-crystal.scalingo.io/
* [x] https://sample-node-express.scalingo.io/ (looks like a Scalingo error page) 
* [x] https://sample-php-lumen.scalingo.io/

**Comment by yannski** [comment]
@EtienneM  please archive this repo after resolving this issue

**Comment by EtienneM** [comment]
Closed in favor of https://github.com/Scalingo/documentation/issues/319
